# Generated by Django 3.0.4 on 2020-04-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='media/')),
                ('event_date', models.DateTimeField(auto_now=True)),
                ('holiday', models.CharField(choices=[('Christmas', 'Christmas')], max_length=256)),
            ],
        ),
    ]
