# Generated by Django 3.0.4 on 2020-04-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageuploadSamplecards',
        ),
    ]
