# Generated by Django 3.0.4 on 2020-04-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='')),
                ('Image_Filename', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='imagepull',
            name='holiday',
        ),
    ]
